apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: sklearn
  name: sklearn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sklearn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: sklearn
    spec:
      containers:
      - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        name: sklearn
        resources: {}